name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.5

    - name: Publish jTelegram
      run: mvn -B -e --settings .github/settings.xml -Dmaven.wagon.http.pool=false -Dgithub.user=${{ secrets.github_user }} -Dgithub.password=${{ secrets.github_pat }} org.codehaus.mojo:versions-maven-plugin:2.3:set -DnewVersion=$VERSION clean deploy
      env:
        VERSION: ${{ steps.get_version.outputs.VERSION }}
    
    - name: Publish javadocs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.github_pat }}
        BRANCH: gh-pages
        FOLDER: jtelegrambotapi-core/target/apidocs
